version: '3.3'
services:
  db:
    env_file:
      - path: ./.env.staging
        required: true
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pug-db'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
