version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pug-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root@admin'
      MYSQL_ROOT_PASSWORD: 'root@admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: